import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { DM_Sans, Raleway } from "next/font/google";
import "./globals.css";
import Header from "@/shared/ui/header";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${raleway.variable} font-sans antialiased`}
      >
        <AntdRegistry>
          <Header />
          {children}
        </AntdRegistry>
      </body>
    </html>
  );
}
