import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { DM_Sans, Raleway } from "next/font/google";
import "../globals.css";
import Header from "@/shared/ui/header";
import { NextIntlClientProvider } from "next-intl";
import { ReactNode } from "react";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocalalizedLayout({
  children,
  params,
}: Readonly<{
  children: ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await import(`../../../messages/${locale}.json`);

  return (
    <html lang={locale}>
      <body
        className={`${dmSans.variable} ${raleway.variable} font-sans antialiased`}
      >
        <NextIntlClientProvider messages={messages.default} locale={locale}>
          <AntdRegistry>
            <Header />
            {children}
          </AntdRegistry>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
